# Generated by Django 4.1 on 2022-09-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologo',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='logo',
        ),
        migrations.AddField(
            model_name='psicologo',
            name='firmaBase64',
            field=models.BinaryField(blank=True, db_column='firma', editable=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='logoBase64',
            field=models.BinaryField(blank=True, db_column='logo', editable=True, null=True),
        ),
    ]
